import { Bool, OpenAPIRoute, Str } from "chanfana";
import { z } from "zod";
import { toJSON } from "../../utils";
import { EventType } from "./types";

interface Env {
  DB: D1Database;
}

export default class AssetCreate extends OpenAPIRoute {
  schema = {
    tags: ["미래 자산"],
    summary: "미래 자산 등록",
    request: {
      body: {
        content: {
          "application/json": {
            schema: z.object({
              // 기본 정보
              name: z.string({
                description: "고객 이름",
              }),
              phone: z.string({
                description: "고객 전화번호",
              }),
              age: z.string({
                description: "나이",
              }),
              agree: z.boolean({
                description: "개인정보 동의",
              }),

              // 소득/지출 정보
              industry_classification: z.string().optional(),
              income: z.string().optional(),
              industry_retirement: z.string().optional(),
              saving: z.string().optional(),
              stock: z.string().optional(),
              pension: z.string().optional(),
              rent: z.string().optional(),
              insurance: z.string().optional(),
              communication: z.string().optional(),
              fixed_etc: z.string().optional(),
              food_expense: z.string().optional(),
              transportation_expense: z.string().optional(),
              healthcare_expense: z.string().optional(),
              variable_etc: z.string().optional(),

              // 자산 정보
              asset_saving: z.string().optional(),
              asset_investment: z.string().optional(),
              asset_etc: z.string().optional(),

              // 부채 정보
              debt_car: z.string().optional(),
              debt_overdraft: z.string().optional(),
              debt_loan: z.string().optional(),
              debt_etc: z.string().optional(),

              // 결혼 계획
              marriage_plan: z.boolean().optional(),
              marriage_age: z.string().optional(),
              ring: z.string().optional(),
              wedding_hall: z.string().optional(),
              studio: z.string().optional(),
              dress_tuxedo: z.string().optional(),
              makeup: z.string().optional(),
              honeymoon: z.string().optional(),

              // 차량 계획
              vehicle_transport_mode: z.string().optional(),
              vehicle_purchase_age: z.string().optional(),
              vehicle_price_domestic: z.string().optional(),
              vehicle_price_foreign: z.string().optional(),
              vehicle_loan_amount: z.string().optional(),
              vehicle_loan_interest: z.string().optional(),

              // 주거 계획
              residence_type: z.string().optional(),
              rent_monthly: z.string().optional(),
              rent_deposit: z.string().optional(),
              house_purchase_age: z.string().optional(),
              residence_area: z.string().optional(),
              housing_price_local: z.string().optional(),
              housing_price_capital: z.string().optional(),
              housing_price_seoul: z.string().optional(),
              housing_price_gangnam: z.string().optional(),
              housing_loan_amount: z.string().optional(),
              housing_loan_interest: z.string().optional(),

              // 자녀 계획
              child_plan: z.boolean().optional(),
              child_count: z.string().optional(),
              first_child_age: z.string().optional(),
              child_age_gap: z.string().optional(),
              disorder_test: z.string().optional(),
              baby_items: z.string().optional(),
              child_insurance: z.string().optional(),
              birth_type: z.string().optional(),
              birth_room: z.string().optional(),
              postpartum_care: z.string().optional(),
              childcare_support: z.string().optional(),
              toys: z.string().optional(),
              first_birthday: z.string().optional(),
              birthday_photo: z.string().optional(),
              infant_education: z.string().optional(),
              kindergarten: z.string().optional(),
              elementary_school: z.string().optional(),
              middle_school: z.string().optional(),
              high_school: z.string().optional(),
              private_highschool: z.string().optional(),
              child_allowance: z.string().optional(),
              university: z.string().optional(),

              // 부모 지원
              parent_count: z.string().optional(),
              parent_allowance: z.string().optional(),
            }),
          },
        },
      },
    },
    responses: {
      "201": {
        description: "자산 정보가 성공적으로 생성됨",
        content: {
          "application/json": {
            schema: z.object({
              series: z.object({
                success: Bool(),
                result: z.object({
                  id: z.string(),
                  name: z.string(),
                  phone: z.string(),
                  age: z.string(),
                  agree: z.boolean(),
                  industry_classification: z.string().optional(),
                  income: z.string().optional(),
                  industry_retirement: z.string().optional(),
                  saving: z.string().optional(),
                  stock: z.string().optional(),
                  pension: z.string().optional(),
                  rent: z.string().optional(),
                  insurance: z.string().optional(),
                  communication: z.string().optional(),
                  fixed_etc: z.string().optional(),
                  food_expense: z.string().optional(),
                  transportation_expense: z.string().optional(),
                  healthcare_expense: z.string().optional(),
                  variable_etc: z.string().optional(),
                  asset_saving: z.string().optional(),
                  asset_investment: z.string().optional(),
                  asset_etc: z.string().optional(),
                  debt_car: z.string().optional(),
                  debt_overdraft: z.string().optional(),
                  debt_loan: z.string().optional(),
                  debt_etc: z.string().optional(),
                  marriage_plan: z.boolean().optional(),
                  marriage_age: z.string().optional(),
                  ring: z.string().optional(),
                  wedding_hall: z.string().optional(),
                  studio: z.string().optional(),
                  dress_tuxedo: z.string().optional(),
                  makeup: z.string().optional(),
                  honeymoon: z.string().optional(),
                  vehicle_transport_mode: z.string().optional(),
                  vehicle_purchase_age: z.string().optional(),
                  vehicle_price_domestic: z.string().optional(),
                  vehicle_price_foreign: z.string().optional(),
                  vehicle_loan_amount: z.string().optional(),
                  vehicle_loan_interest: z.string().optional(),
                  residence_type: z.string().optional(),
                  rent_monthly: z.string().optional(),
                  rent_deposit: z.string().optional(),
                  house_purchase_age: z.string().optional(),
                  residence_area: z.string().optional(),
                  housing_price_local: z.string().optional(),
                  housing_price_capital: z.string().optional(),
                  housing_price_seoul: z.string().optional(),
                  housing_price_gangnam: z.string().optional(),
                  housing_loan_amount: z.string().optional(),
                  housing_loan_interest: z.string().optional(),
                  child_plan: z.boolean().optional(),
                  child_count: z.string().optional(),
                  first_child_age: z.string().optional(),
                  child_age_gap: z.string().optional(),
                  disorder_test: z.string().optional(),
                  baby_items: z.string().optional(),
                  child_insurance: z.string().optional(),
                  birth_type: z.string().optional(),
                  birth_room: z.string().optional(),
                  postpartum_care: z.string().optional(),
                  childcare_support: z.string().optional(),
                  toys: z.string().optional(),
                  first_birthday: z.string().optional(),
                  birthday_photo: z.string().optional(),
                  infant_education: z.string().optional(),
                  kindergarten: z.string().optional(),
                  elementary_school: z.string().optional(),
                  middle_school: z.string().optional(),
                  high_school: z.string().optional(),
                  private_highschool: z.string().optional(),
                  child_allowance: z.string().optional(),
                  university: z.string().optional(),
                  parent_count: z.string().optional(),
                  parent_allowance: z.string().optional(),
                }),
              }),
            }),
          },
        },
      },
      "400": {
        description: "잘못된 요청",
        content: {
          "application/json": {
            schema: z.object({
              series: z.object({
                success: Bool(),
                error: Str(),
              }),
            }),
          },
        },
      },
      "500": {
        description: "서버 오류",
        content: {
          "application/json": {
            schema: z.object({
              series: z.object({
                success: Bool(),
                error: Str(),
              }),
            }),
          },
        },
      },
    },
  };

  async handle(c: { env: Env }) {
    // Get validated data
    const data = await this.getValidatedData<typeof this.schema>();

    // Retrieve the validated request body
    const {
      name,
      phone,
      age,
      agree,
      industry_classification,
      income,
      industry_retirement,
      saving,
      stock,
      pension,
      rent,
      insurance,
      communication,
      fixed_etc,
      food_expense,
      transportation_expense,
      healthcare_expense,
      variable_etc,
      asset_saving,
      asset_investment,
      asset_etc,
      debt_car,
      debt_overdraft,
      debt_loan,
      debt_etc,
      marriage_plan,
      marriage_age,
      ring,
      wedding_hall,
      studio,
      dress_tuxedo,
      makeup,
      honeymoon,
      vehicle_transport_mode,
      vehicle_purchase_age,
      vehicle_price_domestic,
      vehicle_price_foreign,
      vehicle_loan_amount,
      vehicle_loan_interest,
      residence_type,
      rent_monthly,
      rent_deposit,
      house_purchase_age,
      residence_area,
      housing_price_local,
      housing_price_capital,
      housing_price_seoul,
      housing_price_gangnam,
      housing_loan_amount,
      housing_loan_interest,
      child_plan,
      child_count,
      first_child_age,
      child_age_gap,
      disorder_test,
      baby_items,
      child_insurance,
      birth_type,
      birth_room,
      postpartum_care,
      childcare_support,
      toys,
      first_birthday,
      birthday_photo,
      infant_education,
      kindergarten,
      elementary_school,
      middle_school,
      high_school,
      private_highschool,
      child_allowance,
      university,
      parent_count,
      parent_allowance,
    } = data.body;

    // Validate required fields
    // if (!name || !phone || !age || agree === undefined) {
    //   return Response.json(
    //     {
    //       success: false,
    //       error:
    //         "필수 입력값(이름, 전화번호, 나이, 개인정보 동의)이 누락되었습니다",
    //     },
    //     {
    //       status: 400,
    //     }
    //   );
    // }

    const ASSET_CREATE = `
      INSERT INTO ASSET (
        name, phone, age, agree,
        industry_classification, income, industry_retirement,
        saving, stock, pension, rent, insurance, communication,
        fixed_etc, food_expense, transportation_expense,
        healthcare_expense, variable_etc,
        asset_saving, asset_investment, asset_etc,
        debt_car, debt_overdraft, debt_loan, debt_etc,
        marriage_plan, marriage_age, ring, wedding_hall,
        studio, dress_tuxedo, makeup, honeymoon,
        vehicle_transport_mode, vehicle_purchase_age,
        vehicle_price_domestic, vehicle_price_foreign,
        vehicle_loan_amount, vehicle_loan_interest,
        residence_type, rent_monthly, rent_deposit,
        house_purchase_age, residence_area,
        housing_price_local, housing_price_capital,
        housing_price_seoul, housing_price_gangnam,
        housing_loan_amount, housing_loan_interest,
        child_plan, child_count, first_child_age,
        child_age_gap, disorder_test, baby_items,
        child_insurance, birth_type, birth_room,
        postpartum_care, childcare_support, toys,
        first_birthday, birthday_photo, infant_education,
        kindergarten, elementary_school, middle_school,
        high_school, private_highschool, child_allowance,
        university, parent_count, parent_allowance
      ) VALUES (
        ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,
        ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,
        ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,
        ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
      )
    `;

    const { success, meta, results } = await c.env.DB.prepare(ASSET_CREATE)
      .bind(
        name,
        phone,
        age,
        agree,
        industry_classification,
        income,
        industry_retirement,
        saving,
        stock,
        pension,
        rent,
        insurance,
        communication,
        fixed_etc,
        food_expense,
        transportation_expense,
        healthcare_expense,
        variable_etc,
        asset_saving,
        asset_investment,
        asset_etc,
        debt_car,
        debt_overdraft,
        debt_loan,
        debt_etc,
        marriage_plan,
        marriage_age,
        ring,
        wedding_hall,
        studio,
        dress_tuxedo,
        makeup,
        honeymoon,
        vehicle_transport_mode,
        vehicle_purchase_age,
        vehicle_price_domestic,
        vehicle_price_foreign,
        vehicle_loan_amount,
        vehicle_loan_interest,
        residence_type,
        rent_monthly,
        rent_deposit,
        house_purchase_age,
        residence_area,
        housing_price_local,
        housing_price_capital,
        housing_price_seoul,
        housing_price_gangnam,
        housing_loan_amount,
        housing_loan_interest,
        child_plan,
        child_count,
        first_child_age,
        child_age_gap,
        disorder_test,
        baby_items,
        child_insurance,
        birth_type,
        birth_room,
        postpartum_care,
        childcare_support,
        toys,
        first_birthday,
        birthday_photo,
        infant_education,
        kindergarten,
        elementary_school,
        middle_school,
        high_school,
        private_highschool,
        child_allowance,
        university,
        parent_count,
        parent_allowance
      )
      .run();

    if (!success) {
      return Response.json(
        {
          success: false,
          error: "자산 정보 생성 중 오류가 발생했습니다",
        },
        {
          status: 500,
        }
      );
    }

    const result = {
      id: meta.last_row_id,
      name,
      phone,
      age,
      agree,
      industry_classification,
      income,
      industry_retirement,
      saving,
      stock,
      pension,
      rent,
      insurance,
      communication,
      fixed_etc,
      food_expense,
      transportation_expense,
      healthcare_expense,
      variable_etc,
      asset_saving,
      asset_investment,
      asset_etc,
      debt_car,
      debt_overdraft,
      debt_loan,
      debt_etc,
      marriage_plan,
      marriage_age,
      ring,
      wedding_hall,
      studio,
      dress_tuxedo,
      makeup,
      honeymoon,
      vehicle_transport_mode,
      vehicle_purchase_age,
      vehicle_price_domestic,
      vehicle_price_foreign,
      vehicle_loan_amount,
      vehicle_loan_interest,
      residence_type,
      rent_monthly,
      rent_deposit,
      house_purchase_age,
      residence_area,
      housing_price_local,
      housing_price_capital,
      housing_price_seoul,
      housing_price_gangnam,
      housing_loan_amount,
      housing_loan_interest,
      child_plan,
      child_count,
      first_child_age,
      child_age_gap,
      disorder_test,
      baby_items,
      child_insurance,
      birth_type,
      birth_room,
      postpartum_care,
      childcare_support,
      toys,
      first_birthday,
      birthday_photo,
      infant_education,
      kindergarten,
      elementary_school,
      middle_school,
      high_school,
      private_highschool,
      child_allowance,
      university,
      parent_count,
      parent_allowance,
    };

    // return the new asset
    return toJSON(result, 201, "asset");
  }
}
